//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ClassicStartMenuDLL.rc
//
#define IDI_APPICON                     1
#define IDD_RENAME                      102
#define IDC_EDITNAME                    102
#define IDD_RENAMER                     103
#define IDD_LOGOFF                      104
#define IDD_LOGOFFR                     105
#define IDB_SEARCH_ICONS                110
#define IDC_STATICICON                  209
#define IDC_COMBOCOMMAND                239
#define IDC_EDITLABEL                   240
#define IDC_EDITTIP                     241
#define IDC_BUTTONLINK                  242
#define IDC_BUTTONCOMMAND               243
#define IDC_EDITICON                    245
#define IDC_BUTTONICON                  246
#define IDC_STATICCOMMAND               251
#define IDC_STATICLINK                  252
#define IDC_STATICTEXT                  253
#define IDC_STATICINFOTIP               254
#define IDC_ICONN                       256
#define IDC_COMBOLINK                   258
#define IDC_BUTTONRESET                 261
#define IDC_PROMPT                      1015
#define IDC_COMBOSKIN                   1019
#define IDB_ARROWS                      1020
#define IDC_ABOUT                       1020
#define IDC_STATICOPT                   1023
#define IDC_STATICVER                   1025
#define IDC_LABEL                       1047
#define IDC_RADIO2                      1049
#define IDC_TREE2                       1052
#define IDC_SKINOPTIONS                 1052
#define IDC_STATICICON1                 1053
#define IDC_CHECKSORTZA                 1054
#define IDC_CHECKSORTZAREC              1055
#define IDC_CHECKSORTONCE               1056
#define IDC_CHECKOPENUP                 1057
#define IDC_CHECKOPENUPCHILDREN         1058
#define IDC_CHECKOPENUPREC              1058
#define IDC_CHECKNOEXPAND               1059
#define IDC_CHECKMULTICOLUMN            1060
#define IDC_BUTTON1                     1060
#define IDC_CHECKTRACK                  1061
#define IDC_STATICSKIN                  1061
#define IDC_CHECKNOTRACK                1062
#define IDC_STATICALLPROGS              1062
#define IDC_CHECKITEMSFIRST             1063
#define IDC_CHECKINLINE                 1064
#define IDC_CHECK2                      1065
#define IDC_CHECKNOEXT                  1065
#define IDD_CUSTOMMENU                  3001
#define IDS_APP_TITLE                   3001
#define IDD_SKINSETTINGS                3002
#define IDS_SETTINGS_TITLE              3002
#define IDS_SETTINGS_TITLE_VER          3003
#define IDS_NEW_SETTINGS                3004
#define IDS_CTRL_NOTHING                3005
#define IDS_STRING3005                  3005
#define IDS_NO_TEXT                     3005
#define IDS_CTRL_CLASSIC                3006
#define IDS_CTRL_WINDOWS                3007
#define IDS_SETTINGS                    3008
#define IDS_SETTINGS_TIP                3009
#define IDS_SKIN_ERR_UNKNOWN            3010
#define IDS_SKIN_ERR_DISABLE            3011
#define IDS_SKIN_ERR                    3012
#define IDS_SKIN_WARN                   3013
#define IDS_SKIN_ABOUT                  3014
#define IDS_SKIN_FAIL                   3015
#define IDS_SKIN_ERR_BMPRES             3016
#define IDS_SKIN_ERR_BMPFILE            3017
#define IDS_SKIN_ERR_MASKRES            3018
#define IDS_SKIN_ERR_MASKFILE           3019
#define IDS_SKIN_ERR_MASKSIZE           3020
#define IDS_SKIN_ERR_FIND_RES1          3021
#define IDS_SKIN_ERR_LOAD_RES1          3022
#define IDS_SKIN_ERR_LOAD_FILE1         3023
#define IDS_SKIN_ERR_FIND_RES           3024
#define IDS_SKIN_ERR_LOAD_RES           3025
#define IDS_SKIN_ERR_LOAD_FILE          3026
#define IDS_SKIN_ERR_LOAD               3027
#define IDS_SKIN_ERR_VERSION            3028
#define IDS_MENU_TITLE                  3029
#define IDS_DEFAULT_SKIN                3030
#define IDS_CONTROLS_SETTINGS           3031
#define IDS_OPEN_NOTHING                3032
#define IDS_OPEN_NOTHING_TIP            3033
#define IDS_OPEN_CSM                    3034
#define IDS_OPEN_CSM_TIP                3035
#define IDS_OPEN_WSM                    3036
#define IDS_OPEN_WSM_TIP                3037
#define IDS_LCLICK                      3038
#define IDS_LCLICK_TIP                  3039
#define IDS_SHIFT_LCLICK                3040
#define IDS_SHIFT_LCLICK_TIP            3041
#define IDS_WIN_KEY                     3042
#define IDS_WIN_KEY_TIP                 3043
#define IDS_SHIFT_WIN                   3044
#define IDS_SHIFT_WIN_TIP               3045
#define IDS_MCLICK                      3046
#define IDS_MCLICK_TIP                  3047
#define IDS_HOVER                       3048
#define IDS_HOVER_TIP                   3049
#define IDS_HOVER_DELAY                 3050
#define IDS_HOVER_DELAY_TIP             3051
#define IDS_CSM_HOTKEY                  3052
#define IDS_CSM_HOTKEY_TIP              3053
#define IDS_WSM_HOTKEY                  3054
#define IDS_WSM_HOTKEY_TIP              3055
#define IDS_SHOW_ITEMS                  3056
#define IDS_ITEM_HIDE                   3057
#define IDS_ITEM_HIDE_TIP               3058
#define IDS_ITEM_SHOW                   3059
#define IDS_ITEM_SHOW_TIP               3060
#define IDS_ITEM_MENU                   3061
#define IDS_ITEM_MENU_TIP               3062
#define IDS_SHOW_FAVORITES              3063
#define IDS_SHOW_FAVORITES_TIP          3064
#define IDS_SHOW_DOCUMENTS              3065
#define IDS_SHOW_DOCUMENTS_TIP          3066
#define IDS_MAX_DOCS                    3067
#define IDS_MAX_DOCS_TIP                3068
#define IDS_SHOW_USERFILES              3069
#define IDS_SHOW_USERFILES_TIP          3070
#define IDS_SHOW_USERDOCS               3071
#define IDS_SHOW_USERDOCS_TIP           3072
#define IDS_SHOW_USERPICS               3073
#define IDS_SHOW_USERPICS_TIP           3074
#define IDS_SHOW_CP                     3075
#define IDS_SHOW_CP_TIP                 3076
#define IDS_SHOW_NETWORK                3077
#define IDS_SHOW_NETWORK_TIP            3078
#define IDS_SHOW_PRINTERS               3079
#define IDS_SHOW_PRINTERS_TIP           3080
#define IDS_SHOW_SEARCH                 3081
#define IDS_SHOW_SEARCH_TIP             3082
#define IDS_SHOW_HELP                   3083
#define IDS_SHOW_HELP_TIP               3084
#define IDS_SHOW_RUN                    3085
#define IDS_SHOW_RUN_TIP                3086
#define IDS_SHOW_LOGOFF                 3087
#define IDS_SHOW_LOGOFF_TIP             3088
#define IDS_CONFIRM_LOGOFF              3089
#define IDS_CONFIRM_LOGOFF_TIP          3090
#define IDS_SHOW_UNDOCK                 3091
#define IDS_SHOW_UNDOCK_TIP             3092
#define IDS_SHOW_SHUTDOWN               3093
#define IDS_SHOW_SHUTDOWN_TIP           3094
#define IDS_SHOW_RSHUTDOWN              3095
#define IDS_SHOW_RSHUTDOWN_TIP          3096
#define IDS_SHOW_RECENT                 3097
#define IDS_SHOW_RECENT_TIP             3098
#define IDS_MAX_PROGS                   3099
#define IDS_MAX_PROGS_TIP               3100
#define IDS_RECENT_TOP                  3101
#define IDS_RECENT_TOP_TIP              3102
#define IDS_RECENT_KEYS                 3103
#define IDS_RECENT_KEYS_TIP             3104
#define IDS_KEY_NOTHING                 3105
#define IDS_KEY_NOTHING_TIP             3106
#define IDS_KEY_NORMAL                  3107
#define IDS_KEY_NORMAL_TIP              3108
#define IDS_KEY_DIGITS                  3109
#define IDS_KEY_DIGITS_TIP              3110
#define IDS_KEY_HIDDEN                  3111
#define IDS_KEY_HIDDEN_TIP              3112
#define IDS_BEHAVIOR_SETTINGS           3113
#define IDS_EXPAND_LINKS                3114
#define IDS_EXPAND_LINKS_TIP            3115
#define IDS_MENU_DELAY                  3116
#define IDS_MENU_DELAY_TIP              3117
#define IDS_TIP_DELAY                   3118
#define IDS_TIP_DELAY_TIP               3119
#define IDS_FTIP_DELAY                  3120
#define IDS_FTIP_DELAY_TIP              3121
#define IDS_ANIM_NONE                   3122
#define IDS_ANIM_NONE_TIP               3123
#define IDS_ANIM_FADE                   3124
#define IDS_ANIM_FADE_TIP               3125
#define IDS_ANIM_SLIDE                  3126
#define IDS_ANIM_SLIDE_TIP              3127
#define IDS_ANIMATION                   3128
#define IDS_ANIMATION_TIP               3129
#define IDS_ANIM_SPEED                  3130
#define IDS_ANIM_SPEED_TIP              3131
#define IDS_SUB_ANIMATION               3132
#define IDS_SUB_ANIMATION_TIP           3133
#define IDS_SUB_ANIM_SPEED              3134
#define IDS_SUB_ANIM_SPEED_TIP          3135
#define IDS_SCROLL_SPEED                3136
#define IDS_SCROLL_SPEED_TIP            3137
#define IDS_SUB_SCROLL_SPEED            3138
#define IDS_SUB_SCROLL_SPEED_TIP        3139
#define IDS_FADE_SPEED                  3140
#define IDS_FADE_SPEED_TIP              3141
#define IDS_DRAG_DELAY                  3142
#define IDS_DRAG_DELAY_TIP              3143
#define IDS_ACCESSIBILITY               3144
#define IDS_ACCESSIBILITY_TIP           3145
#define IDS_NEXTTASKBAR                 3146
#define IDS_NEXTTASKBAR_TIP             3147
#define IDS_SEARCH_COMMAND              3148
#define IDS_SEARCH_COMMAND_TIP          3149
#define IDS_CASCADE_MENU                3150
#define IDS_CASCADE_MENU_TIP            3151
#define IDS_CACHE_ICONS                 3152
#define IDS_CACHE_ICONS_TIP             3153
#define IDS_SKIN_ERRORS                 3154
#define IDS_SKIN_ERRORS_TIP             3155
#define IDS_LOOK_SETTINGS               3156
#define IDS_MENU_WIDTH                  3157
#define IDS_MENU_WIDTH_TIP              3158
#define IDS_SUBMENU_WIDTH               3159
#define IDS_SUBMENU_WIDTH_TIP           3160
#define IDS_SAME_COLUMNS                3161
#define IDS_SAME_COLUMNS_TIP            3162
#define IDS_MENU_CAPTION                3163
#define IDS_MENU_CAPTION_TIP            3164
#define IDS_MENU_USERNAME               3165
#define IDS_MENU_USERNAME_TIP           3166
#define IDS_PIC_COMMAND                 3167
#define IDS_PIC_COMMAND_TIP             3168
#define IDS_NAME_COMMAND                3169
#define IDS_NAME_COMMAND_TIP            3170
#define IDS_SMALL_SIZE_SM               3171
#define IDS_SMALL_SIZE_SM_TIP           3172
#define IDS_LARGE_SIZE_SM               3173
#define IDS_LARGE_SIZE_SM_TIP           3174
#define IDS_NUMERIC_SORT                3175
#define IDS_NUMERIC_SORT_TIP            3176
#define IDS_FONT_SMOOTHING              3177
#define IDS_FONT_SMOOTHING_TIP          3178
#define IDS_SMOOTH_DEFAULT              3179
#define IDS_SMOOTH_DEFAULT_TIP          3180
#define IDS_SMOOTH_NONE                 3181
#define IDS_SMOOTH_NONE_TIP             3182
#define IDS_SMOOTH_STD                  3183
#define IDS_SMOOTH_STD_TIP              3184
#define IDS_SMOOTH_CLEAR                3185
#define IDS_SMOOTH_CLEAR_TIP            3186
#define IDS_SECURITY_SETTINGS           3187
#define IDS_DRAG_DROP                   3188
#define IDS_DRAG_DROP_TIP               3189
#define IDS_CONTEXT_MENU                3190
#define IDS_CONTEXT_MENU_TIP            3191
#define IDS_NEW_FOLDER                  3192
#define IDS_NEW_FOLDER_TIP              3193
#define IDS_EXIT                        3194
#define IDS_EXIT_TIP                    3195
#define IDS_SOUND_SETTINGS              3196
#define IDS_SOUND_MAIN                  3197
#define IDS_SOUND_MAIN_TIP              3198
#define IDS_SOUND_POPUP                 3199
#define IDS_SOUND_POPUP_TIP             3200
#define IDS_SOUND_COMMAND               3201
#define IDS_SOUND_COMMAND_TIP           3202
#define IDS_SOUND_DROP                  3203
#define IDS_SOUND_DROP_TIP              3204
#define IDS_WSM_SETTINGS                3205
#define IDS_CASCADE_ALL                 3206
#define IDS_CASCADE_ALL_TIP             3207
#define IDS_ALL_DELAY                   3208
#define IDS_ALL_DELAY_TIP               3209
#define IDS_ALL_SELECT                  3210
#define IDS_ALL_SELECT_TIP              3211
#define IDS_SELECT_SEARCH               3212
#define IDS_SELECT_SEARCH_TIP           3213
#define IDS_SELECT_BUTTON               3214
#define IDS_SELECT_BUTTON_TIP           3215
#define IDS_SKIN_SETTINGS               3216
#define IDS_ALL_SKIN_SETTINGS           3217
#define IDS_CUSTOM_SETTINGS             3218
#define IDS_LANGUAGE_SETTINGS_SM        3219
#define IDS_SCROLL_TYPE                 3220
#define IDS_SCROLL_TYPE_TIP             3221
#define IDS_SCROLL_NO                   3222
#define IDS_SCROLL_NO_TIP               3223
#define IDS_SCROLL_YES                  3224
#define IDS_SCROLL_YES_TIP              3225
#define IDS_SCROLL_AUTO                 3226
#define IDS_SCROLL_AUTO_TIP             3227
#define IDS_ANIM_RANDOM                 3228
#define IDS_ANIM_RANDOM_TIP             3229
#define IDC_SKINVARIATION               3230
#define IDS_COMMAND_TIP                 3231
#define IDS_LINK_TIP                    3232
#define IDS_TEXT_TIP                    3233
#define IDS_TIP_TIP                     3234
#define IDS_ICON_TIP                    3235
#define IDS_SORTZA_TIP                  3236
#define IDS_SORTZAREC_TIP               3237
#define IDS_SORTONCE_TIP                3238
#define IDS_OPENUP_TIP                  3239
#define IDS_OPENUPREC_TIP               3240
#define IDS_NOEXPAND_TIP                3241
#define IDS_MULTICOLUMN_TIP             3242
#define IDS_TRACK_TIP                   3243
#define IDS_NOTRACK_TIP                 3244
#define IDS_ITEMSFIRST_TIP              3245
#define IDS_MAIN_SORTZA                 3246
#define IDS_MAIN_SORTONCE               3247
#define IDS_SEPARATOR_TIP               3248
#define IDS_BREAK_TIP                   3249
#define IDS_PADDING_TIP                 3250
#define IDS_PROGRAMS_TIP                3251
#define IDS_FAVORITES_TIP               3252
#define IDS_DOCUMENTS_TIP               3253
#define IDS_USERFILES_TIP               3254
#define IDS_USERDOCS_TIP                3255
#define IDS_USERPICS_TIP                3256
#define IDS_CONTROLPANEL_TIP            3257
#define IDS_CONTROLPANEL2_TIP           3258
#define IDS_SECURITY_TIP                3259
#define IDS_NETWORK_TIP                 3260
#define IDS_PRINTERS_TIP                3261
#define IDS_RUN_TIP                     3262
#define IDS_HELP_TIP                    3263
#define IDS_LOGOFF_TIP                  3264
#define IDS_UNDOCK_TIP                  3265
#define IDS_DISCONNECT_TIP              3266
#define IDS_SHUTDOWNBOX_TIP             3267
#define IDS_SEARCHFI_TIP                3268
#define IDS_SEARCHPR_TIP                3269
#define IDS_SEARCHCO_TIP                3270
#define IDS_SEARCHPE_TIP                3271
#define IDS_TASKBAR_TIP                 3272
#define IDS_MENU_TIP                    3273
#define IDS_RECENT_TIP                  3274
#define IDS_SLEEP_TIP                   3275
#define IDS_HIBERNATE_TIP               3276
#define IDS_RESTART_TIP                 3277
#define IDS_SHUTDOWN_TIP                3278
#define IDS_SWITCH_TIP                  3279
#define IDS_CUSTOM_TIP                  3280
#define IDS_SEARCH_TIP                  3281
#define IDS_SETTINGS_MENU_TIP           3282
#define IDS_FEATURES_TIP                3283
#define IDS_RESTORE_TIP                 3284
#define IDS_SEARCH_BOX_TIP              3285
#define IDS_SEARCH_BOX                  3286
#define IDS_SHOW_SEARCH_BOX             3287
#define IDS_SHOW_SEARCH_BOX_TIP         3288
#define IDS_SEARCH_BOX_HIDE             3289
#define IDS_SEARCH_BOX_HIDE_TIP         3290
#define IDS_SEARCH_BOX_SHOW             3291
#define IDS_SEARCH_BOX_SHOW_TIP         3292
#define IDS_SEARCH_BOX_TAB              3293
#define IDS_SEARCH_BOX_TAB_TIP          3294
#define IDS_SEARCH_BOX_SEL              3295
#define IDS_SEARCH_BOX_SEL_TIP          3296
#define IDS_SEARCH_CP                   3297
#define IDS_SEARCH_CP_TIP               3298
#define IDS_SEARCH_PATH                 3299
#define IDS_SEARCH_PATH_TIP             3300
#define IDS_SUB_WORD                    3301
#define IDS_SUB_WORD_TIP                3302
#define IDS_SEARCH_TRACK                3303
#define IDS_SEARCH_TRACK_TIP            3304
#define IDS_SEARCH_MAX                  3305
#define IDS_SEARCH_MAX_TIP              3306
#define IDS_SEARCH_AUTO                 3307
#define IDS_SEARCH_AUTO_TIP             3308
#define IDS_INLINE_TIP                  3309
#define IDS_NOEXTENSIONS_TIP            3310
#define IDS_DELAY_ICONS                 3311
#define IDS_DELAY_ICONS_TIP             3312
#define IDS_SHOW_FAVORITES_TIP2         3313
#define IDS_SHOW_DOCUMENTS_TIP2         3314
#define IDS_SHOW_USERFILES_TIP2         3315
#define IDS_SHOW_USERDOCS_TIP2          3316
#define IDS_SHOW_USERPICS_TIP2          3317
#define IDS_SHOW_CP_TIP2                3318
#define IDS_SHOW_NETWORK_TIP2           3319
#define IDS_SHOW_PRINTERS_TIP2          3320
#define IDS_SHOW_SHUTDOWN_TIP2          3321
#define IDS_SHOW_SEARCH_BOX_TIP2        3322
#define IDS_SHOW_SEARCH_TIP2            3323
#define IDS_SHOW_HELP_TIP2              3324
#define IDS_SHOW_RUN_TIP2               3325
#define IDS_SHOW_LOGOFF_TIP2            3326
#define IDS_SHOW_UNDOCK_TIP2            3327
#define IDS_LOCK_TIP                    3328

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
